### ISSUE TITLE
AUTHORIZE request returns code 4001

### ISSUE THREAD

**Issue by zspri** [devakira/py-rpc#1]
```
ws://127.0.0.1:6463?v=1&client_id=392113753677889536&=encoding=json
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    asyncio.get_event_loop().run_until_complete(client_setup())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "test.py", line 5, in client_setup
    await c.authenticate()
  File "C:\Users\Admin\Documents\Git\py-rpc\pyrpc\rpc.py", line 37, in authenticate
    raw_res = await ws.recv()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 319, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4001, reason = Invalid Origin.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x02D8E750>
```

**Comment by zaidi-01** [comment]
Welp at least someone attempted this

**Comment by zspri** [comment]
So close, yet so far

--
I got an email from a Discord dev saying that websocket connections are for whitelisted games only, and other games have to use ipc which I don't think is documented...

**Comment by zaidi-01** [comment]
It says in their RPC documentation that its BETA only so u have you have to sign up for it

I don't get how they did it but one of the Java libraries are made from scratch. We'll have to look into that to find out

**Comment by zspri** [comment]
I think Discord.js has rpc support also, we could look from there

**Comment by MCOfficer** [comment]
i had to look twice, but found the [documentation for the SDK](https://discordapp.com/developers/docs/rich-presence/how-to).
there is also a [java lib](https://github.com/MinnDevelopment/java-discord-rpc) and the [node.js module](https://github.com/discordjs/RPC) mentioned above. i tried reading into those, but can't figure out what exactly happens.

edit: also found two [python](https://github.com/GiovanniMCMXCIX/PyDiscordRPC) [projects](https://github.com/Maselkov/GW2RPC) using rpc (the first is the most promising).

**Comment by zspri** [comment]
We could always try something similar to that, though I agree with you that it's hard to understand what is happening.

**Comment by qwertyquerty** [comment]
@Nanomotion check out how I've accomplished this. Mine isn't the best coded library in the world, but it works. Even so, I would be interested to see another one made. Here it is: https://github.com/qwertyquerty/pypresence
